name: '微信小程序上传 Action'
description: '自动化上传微信小程序代码'
author: 'ilaipi'

inputs:
  appid:
    description: '小程序的 AppID'
    required: true
  private_key:
    description: '小程序代码上传密钥'
    required: true
  project_path:
    description: '小程序项目路径'
    required: false
    default: './'
  version:
    description: '发布版本号'
    required: false
    default: '1.0.0'

runs:
  using: 'node22'
  main: './dist/index.js'

branding:
  icon: 'upload-cloud'
  color: 'blue'