name: 'WeChat MiniProgram Upload Action'
description: 'Upload WeChat MiniProgram using miniprogram-ci'
author: 'ilaipi'

inputs:
  appid:
    description: '小程序的 AppID'
    required: true
  private_key:
    description: '小程序代码上传密钥'
    required: false
  private_key_path:
    description: '小程序代码上传密钥文件路径'
    required: false
  project_path:
    description: '小程序项目路径'
    required: false
    default: './'
  version:
    description: '发布版本号'
    required: false
    default: '1.0.0'
  desc:
    description: '项目备注'
    required: false
    default: ''

runs:
  using: 'node20'
  main: './dist/index.js'

branding:
  icon: 'upload-cloud'
  color: 'blue'